'use strict';
const viewStorage={getItem(k){try{return localStorage.getItem(k)}catch{return null}},setItem(k,v){try{localStorage.setItem(k,v)}catch{}},removeItem(k){try{localStorage.removeItem(k)}catch{}}};
const ARINBrief=(()=>{
 const categories=['시장·경제','반도체·AI','국제','주요 뉴스'];
 function read(k,f){try{return JSON.parse(viewStorage.getItem(k))||f}catch{return f}}
 let interests=read('view-interests',[]),seen=read('view-read',[]),pool=[],busy=false,last=null;
 if(!Array.isArray(interests))interests=[];if(!Array.isArray(seen))seen=[];
 const safeLink=s=>{try{const u=new URL(s);return /^https?:$/.test(u.protocol)?u.href:'#'}catch{return '#'}};
 const key=x=>x.title.toLowerCase().replace(/[^0-9a-z가-힣]/g,'');
 function select(items){const used=new Set(),counts={};return items.filter(x=>typeof x.title==='string'&&safeLink(x.link)!=='#').map((x,i)=>{const published=Date.parse(x.published),fresh=Number.isFinite(published)?Math.max(0,2-(Date.now()-published)/86400000):0;return {...x,rank:Number(x.importance||1)+fresh+(interests.includes(x.category)?3:0)+(seen.includes(key(x))?0:4)-i/100}}).sort((a,b)=>b.rank-a.rank).filter(x=>{const k=key(x);if(used.has(k)||(counts[x.category]||0)>=2)return false;used.add(k);counts[x.category]=(counts[x.category]||0)+1;return true}).slice(0,3)}
 function render(){const list=document.querySelector('#morning-list');list.replaceChildren();const items=select(pool);for(const it of items){const a=document.createElement('a');a.className='morningItem';a.href=safeLink(it.link);a.target='_blank';a.rel='noopener noreferrer';const b=document.createElement('b'),title=document.createElement('span'),p=document.createElement('p'),small=document.createElement('small');b.textContent=`${it.category} · ${it.source}`;title.textContent=it.title;p.textContent='아린: '+it.comment;small.textContent=seen.includes(key(it))?'읽은 소식 · 원문 다시 보기':'새로 확인할 소식 · 원문 보기';a.append(b,title,p,small);a.addEventListener('click',()=>{seen=[key(it),...seen.filter(x=>x!==key(it))].slice(0,120);viewStorage.setItem('view-read',JSON.stringify(seen));small.textContent='읽은 소식 · 원문 다시 보기'});list.append(a)}if(!items.length)list.textContent='아직 고를 수 있는 소식이 없어요. 잠시 후 다시 확인해주세요.'}
 async function refresh(){if(busy)return;busy=true;const status=document.querySelector('#morning-status');status.textContent='소식 고르는 중';try{const r=await fetch('/api/morning',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();if(!Array.isArray(d.items)||!d.items.length)throw Error('empty');pool=d.items;last=d.updatedAt;render();status.textContent=d.errors?.length?'일부 출처 확인됨':'핵심 3개';document.querySelector('#morning-meta').textContent=`${new Date(last).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 확인 · ${d.note} · 단톡방/개인 커뮤니티 연결은 아직 없어요.`}catch{status.textContent=last?'갱신 실패 · 이전 브리핑':'연결을 확인해주세요';if(!last)document.querySelector('#morning-list').textContent='최신 소식을 불러오지 못했어요. 다시 골라보기를 눌러주세요.'}finally{busy=false}}
 function init(){for(const c of categories){const b=document.createElement('button');b.className='btn secondary';b.textContent=c;b.setAttribute('aria-pressed',interests.includes(c));b.onclick=()=>{interests=interests.includes(c)?interests.filter(x=>x!==c):[...interests,c];viewStorage.setItem('view-interests',JSON.stringify(interests));b.setAttribute('aria-pressed',interests.includes(c));if(pool.length)render()};document.querySelector('#interests').append(b)}document.querySelector('#brief-refresh').onclick=refresh;const select=document.querySelector('#view-theme');select.value=viewStorage.getItem('view-theme')||'auto';function theme(){const h=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',hour:'numeric',hourCycle:'h23'}).format(new Date()));document.body.classList.toggle('night',select.value==='night'||select.value==='auto'&&(h>=19||h<7))}select.onchange=()=>{viewStorage.setItem('view-theme',select.value);theme()};theme();setInterval(theme,60000)}
 document.addEventListener('DOMContentLoaded',init);return {refresh,safeLink,select};
})();
